### ISSUE TITLE
Invalid grant type for client: implicit

### ISSUE THREAD

**Issue by Shadowman4205** [edwinf/oidc-client-node#8]
I am getting this error when i try login by ur example where i can change implicity to GrantTypes.HybridAndClientCredentials in identity server. Is this possible or i have change 

> AllowedGrantTypes = GrantTypes.HybridAndClientCredentials,
on identity server?

**Comment by edwinf** [comment]
I do not know the answer to that one, sorry.  I've never tried to use that combination.

**Comment by Shadowman4205** [comment]
i did this on Identity server AllowedGrantTypes = GrantTypes.HybridAndClientCredentials for now, and it worked
